### ISSUE TITLE
KeyError: 'GL000008.2'

### ISSUE THREAD

**Issue by aojielian** [tjiangHIT/cuteSV#121]
i got this error using following command:
cuteSV --retain_work_dir --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 100 --diff_ratio_merging_DEL 0.3 /data_exp/ONT/GrandOmics/GrandOmics_BAM/aln_fastq_DBM19A4448_1.sorted.bam /data/a1lian/RNA_seq_database/GRCh37.primary_assembly.genome.fa /data_exp/ONT/GrandOmics/cuteSV_VCFs/aln_fastq_DBM19A4448_1.vcf /data_exp/ONT/GrandOmics/tmp_dir

error like:
2023-05-23 14:48:26,714 [INFO] Finished chr6-chrY:TRA/BND.
2023-05-23 14:48:26,715 [INFO] Finished chr7-chr8:TRA/BND.
2023-05-23 14:48:26,715 [INFO] Finished chrX-chrY:TRA/BND.
2023-05-23 14:48:26,729 [INFO] Writing to your output file.
2023-05-23 14:48:26,831 [INFO] Loading reference genome...
Traceback (most recent call last):
  File "/home/a1lian/anaconda3/envs/cutesv/bin/cuteSV", line 877, in <module>
    run(sys.argv[1:])
  File "/home/a1lian/anaconda3/envs/cutesv/bin/cuteSV", line 873, in run
    main_ctrl(args, argv)
  File "/home/a1lian/anaconda3/envs/cutesv/bin/cuteSV", line 851, in main_ctrl
    generate_output(args, semi_result, contigINFO, argv, ref_g)	
  File "/home/a1lian/anaconda3/envs/cutesv/lib/python3.9/site-packages/cuteSV/cuteSV_genotype.py", line 285, in generate_output
    REF = str(ref_g[i[0]].seq[int(i[2])]),
KeyError: 'GL000008.2'

**Comment by Meltpinkg** [comment]
Hello, @aojielian 

The input reference should be concordant with the reference genome which the input bam is aligned to. The error may caused by the chromosome GL000008.2 doesn't exist in the input reference.
Hope it will help.

Best,
Shuqi

**Comment by jiadong324** [comment]
I have similar issue, and here is the error ```No such file or directory: 'GRCh38/HG01928/results/chr14_GL000009v2_random.pickle'```

But I used the same reference as the one used for read alignments. I also found that cutesv actually processed the reads aligned to contig ```chr14_GL000009v2_random```:

```
2024-03-29 18:30:34,952 [INFO] Finished chr14_GL000009v2_random:0-201709.
2024-03-29 18:33:05,929 [INFO] Finished chr14_GL000009v2_random:DEL.
2024-03-29 18:33:10,861 [INFO] Finished chr14_GL000009v2_random:INS.
2024-03-29 18:33:18,328 [INFO] Finished chr14_GL000009v2_random-chr15:TRA/BND.
2024-03-29 18:33:18,328 [INFO] Finished chr14_GL000009v2_random-chr17:TRA/BND.
2024-03-29 18:33:18,328 [INFO] Finished chr14_GL000009v2_random-chr2:TRA/BND.
2024-03-29 18:33:18,328 [INFO] Finished chr14_GL000009v2_random-chr21:TRA/BND.
2024-03-29 18:33:18,765 [INFO] Finished chr14_GL000009v2_random-chr4_GL000008v2_random:TRA/BND.
2024-03-29 18:33:19,063 [INFO] Finished chr14_GL000009v2_random-chr8:TRA/BND.
2024-03-29 18:33:19,063 [INFO] Finished chr14_GL000009v2_random-chrUn_GL000214v1:TRA/BND.
2024-03-29 18:33:19,063 [INFO] Finished chr14_GL000009v2_random-chrUn_KI270751v1:TRA/BND.
2024-03-29 18:33:19,063 [INFO] Finished chr14_GL000009v2_random-chrY:TRA/BND.
```
Looking forward to your reply! Thanks!

**Comment by Meltpinkg** [comment]
Hello, @jiadong324 

Thanks for bringing this to me! We fixed this error and updated the codes in GitHub. You can git clone the newest codes and reinstall cuteSV via `python setup.py install`. Also, I'm planning to update the version in pip/conda today to bring more convenience.
Hope it will help!

Best,
Shuqi
