### ISSUE TITLE
cuteSV fails to output the result due to computational resources

### ISSUE THREAD

**Issue by bojan-balic-sbg** [tjiangHIT/cuteSV#139]
Hello, it in testing the tool there have been instances where cuteSV fails in relation to the setting of computational resources like RAM and CPU running on Amazon instances. Setting CPU instance requirement to 30 and `threads` parameter to 30 vs 32 and 32 respectively, produces varying results (success for 30 and fail for 32).

Below is the error log from one of the failed runs

```
Writing to your output file.
Traceback (most recent call last):
	File "/usr/local/bin/cuteSV", line 1267, in <module>
		run(sys.argv[1:])
	File "/usr/local/bin/cuteSV", line 1263, in run
		main_ctrl(args, argv)
	File "/usr/local/bin/cuteSV", line 1230, in main_ctrl
		with open("%sresults/%s.pickle"%(temporary_dir,chrom), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 
'/results/E.coli-MG1655-K12NC_000913.3.pickle'
```

**Comment by CoREse** [comment]
Hi, @bojan-balic-sbg,

Thanks for reaching out, to further investigate the problem, could you please provide the whole command lines and the whole logs of the failed runs? Thanks.

Best regards,
CRE
