### ISSUE TITLE
Missing pickle file

### ISSUE THREAD

**Issue by mnshgl0110** [tjiangHIT/cuteSV#158]
Hi,
I am trying to run cutesv on human HG002 genome. But I am getting the missing pickle file error:
```FileNotFoundError: [Errno 2] No such file or directory: 'hg002/results/KMT2C_chr13_10688343_10754814.pickle'```
[cutesv.log](https://github.com/user-attachments/files/18039037/cutesv.log)
Based on the suggestions [here](https://github.com/tjiangHIT/cuteSV/issues/138), I have tried conda as well as git install. Further, I also tried different number to threads (from [here](https://github.com/tjiangHIT/cuteSV/issues/139)), but that did not work either.
Any suggestions, how can I make it work?

**Comment by Meltpinkg** [comment]
Hello, @mnshgl0110 

This may caused by the reference used in the read alignment not equaling the reference used in running cuteSV. Please ensure the reference chromosomes in the _read alignment_ and _SV calling_ is the same.
Hope it will help!

Best,
Shuqi

**Comment by mulderdt** [comment]
Hi, I am getting the same issue since moving from cuteSV 2.0.3 to 2.1.1.

Most samples work fine. I have checked that the reference matches alignment and cuteSV process.

I have seen it fail on chr17.pickle and on chr2.pickle.

It seems to be transient and if I just rerun it it works fine. It doesn't look to be a resources issue.

Thanks,

## see error below

ERROR ~ Error executing process > 'cuteSV_single (LR-115_father-F139924)'

Caused by:
  Process `cuteSV_single (LR-115_father-F139924)` terminated with an error exit status (1)

Command executed:

  cuteSV         --sample LR-115_father-F139924         --threads 4         -md 500 -mi 500 -s 5 -L -1 --genotype         F139924_1_lane.bam hg38_no_alt.fa LR-115_father-F139924.vcf .

Command exit status:
  1

Command output:
  (empty)

Command error:
  2025-01-06 01:19:20,555 [INFO] Finished chrUn_KI270751v1-chrX:TRA/BND.
  2025-01-06 01:19:20,555 [INFO] Finished chrUn_KI270751v1-chrY:TRA/BND.
  2025-01-06 01:19:20,556 [INFO] Finished chrUn_KI270755v1-chrX:TRA/BND.
  2025-01-06 01:19:20,557 [INFO] Finished chrUn_KI270756v1-chrY:TRA/BND.
  2025-01-06 01:19:20,557 [INFO] Finished chrUn_KI270757v1-chrX:TRA/BND.
  2025-01-06 01:19:20,557 [INFO] Finished chrUn_KI270757v1-chrY:TRA/BND.
  2025-01-06 01:19:20,580 [INFO] Finished chr4-chrY:TRA/BND.
  2025-01-06 01:19:20,638 [INFO] Finished chr3-chrUn_GL000224v1:TRA/BND.
  2025-01-06 01:19:20,638 [INFO] Finished chr3-chrUn_GL000226v1:TRA/BND.
  2025-01-06 01:19:20,638 [INFO] Finished chr3-chrUn_KI270333v1:TRA/BND.
  2025-01-06 01:19:20,638 [INFO] Finished chr3-chrUn_KI270336v1:TRA/BND.
  2025-01-06 01:19:20,654 [INFO] Finished chrX-chrY:TRA/BND.
  2025-01-06 01:19:20,847 [INFO] Finished chr3-chrUn_KI270337v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270362v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270435v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270438v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270442v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270467v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270510v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270519v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270584v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270589v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270590v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270741v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270742v1:TRA/BND.
  2025-01-06 01:19:20,848 [INFO] Finished chr3-chrUn_KI270743v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270744v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270745v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270746v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270747v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270748v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270749v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270750v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270751v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270754v1:TRA/BND.
  2025-01-06 01:19:20,849 [INFO] Finished chr3-chrUn_KI270756v1:TRA/BND.
  2025-01-06 01:19:21,147 [INFO] Finished chrUn_KI270743v1-chrUn_KI270744v1:TRA/BND.
  2025-01-06 01:19:21,147 [INFO] Finished chrUn_KI270743v1-chrX:TRA/BND.
  2025-01-06 01:19:21,178 [INFO] Finished chr3-chrUn_KI270757v1:TRA/BND.
  2025-01-06 01:19:21,937 [INFO] Finished chr3-chrX:TRA/BND.
  2025-01-06 01:19:22,202 [INFO] Finished chr3-chrY:TRA/BND.
  2025-01-06 01:19:22,245 [INFO] Writing to your output file.
  Traceback (most recent call last):
    File "/usr/local/bin/cuteSV", line 1269, in <module>
      run(sys.argv[1:])
    File "/usr/local/bin/cuteSV", line 1265, in run
      main_ctrl(args, argv)
    File "/usr/local/bin/cuteSV", line 1232, in main_ctrl
      with open("%sresults/%s.pickle"%(temporary_dir,chrom), "rb") as f:
  FileNotFoundError: [Errno 2] No such file or directory: './results/chr2.pickle'

##

**Comment by Meltpinkg** [comment]
Hello, @mulderdt 

Sorry for my late reply. I will focus on this question and repair it in this week.

Best,
Shuqi

**Comment by Lupphes** [comment]
Hello, it seems that I have the same issue as was described with version 2.1.2

```
Traceback (most recent call last):
  File "/scratch.ssd/luppo/job_10621375.pbs-m1/.conda_next/env-bbd419b6a0312844-f62cc41dcb22731dc1d7ae3e0b3842ed/bin/cuteSV", line 1260, in <module>
    run(sys.argv[1:])
  File "/scratch.ssd/luppo/job_10621375.pbs-m1/.conda_next/env-bbd419b6a0312844-f62cc41dcb22731dc1d7ae3e0b3842ed/bin/cuteSV", line 1256, in run
    main_ctrl(args, argv)
  File "/scratch.ssd/luppo/job_10621375.pbs-m1/.conda_next/env-bbd419b6a0312844-f62cc41dcb22731dc1d7ae3e0b3842ed/bin/cuteSV", line 1222, in main_ctrl
    raise FileNotFoundError("[Errno 2] No such directory: %sresults/%s.pickle"%(temporary_dir,chrom))
FileNotFoundError: [Errno 2] No such directory: ./results/NC_091688.1.pickle
```

```
#!/usr/bin/env bash -C -e -u -o pipefail
cuteSV         SRR30001036.bam \
    GCF_041296265.fna \
    SRR30001036_sas_cutesv.vcf \
    . \
    --threads 12 \
    --max_cluster_bias_INS 1000 --diff_ratio_merging_INS 0.9 --max_cluster_bias_DEL 1000 --diff_ratio_merging_DEL 0.5 --report_readid --max_split_parts -1 --sample cutesv_report_sample --genotype
cat <<-END_VERSIONS > versions.yml
"NFCORE_EUKAVARIZER:EUKAVARIZER:SV_CALLING_CUTESV:CUTESV":
    cuteSV: $( cuteSV --version 2>&1 | sed 's/cuteSV //g' )
END_VERSIONS
```

**Comment by Meltpinkg** [comment]
Hello, @Lupphes 

Sorry for my late reply. Since the error appears unstable and transient, I found it hard to reproduce and debug this issue. We have implemented enhanced error detection and handling mechanisms in the latest release of cuteSV, which has been updated on GitHub. If you're still experiencing this problem, you can: (1) execute the updated version of cuteSV from the GitHub repository, (2) check log files for "_Finished ... output_" lines (where ... is the problematic chromosome). In addition, sharing a minimal dataset that reproduces the error would greatly help our investigation.
We'll continue monitoring this issue and appreciate your feedback.

Best regards,
Shuqi

**Comment by Meltpinkg** [comment]
Hello, @superdaa 

It seems like a problem caused by the alt contigs. Could you provide the total running logs or the resource of the input BAM file? It would be more convenient for me to reproduce and locate the issue. We'll continue monitoring this issue and appreciate your feedback.

Best regards,
Shuqi

**Comment by thom-99** [comment]
commenting on this issue,
I had a similar issue when running my pipeline with version 2.1.2
I have tried to downgrade to version 1.0.13 and it runs without errors. 

perhaps it can help, cheers.

**Comment by mulderdt** [comment]
@Meltpinkg I solved this issue on a set of samples by changing threads to 1. Which is obviously not ideal.

When I run it, it's often a different pickle file missing. With a re-run it sometimes fixes it. With this set it was always failing until setting cpus to 1. In this case I was doing targeted calling with -include_bed so probably few calls were being made. For me it was often a primary contig and not an alt contig.

Perhaps one of the threads lags behind and has yet to write its output pickle file when the process starts working on the next step. Changing threads to 1 and solving the issue would suggest something like this. It could also be on a HPC that the write takes too long or something across NFS so it just needs to wait a bit.

I did try the latest version 2.1.3 first prior to changing threads to 1 and that didn't solve the issue.

**Comment by awgymer** [comment]
**EDIT:** this is a subtly different issue caused by #176 but some of the points about pool usage are still possibly relevant here

I am seeing this issue repeatably (same error in multiple runs, at same point):

```
2026-03-26 02:33:50,837 [INFO] Rebuilding signatures of structural variants.                     
multiprocessing.pool.RemoteTraceback:                                                            
"""                                                                                              
Traceback (most recent call last):                                                               
  File "/opt/conda/lib/python3.11/multiprocessing/pool.py", line 125, in worker                  
    result = (True, func(*args, **kwds))                                                         
                    ^^^^^^^^^^^^^^^^^^^                                                          
  File "/opt/conda/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar                  
    return list(map(*args))                                                                      
           ^^^^^^^^^^^^^^^^                                                                      
  File "/opt/conda/bin/cuteSV", line 750, in process_process_sigs_type                           
    with open("%ssignatures/%s%s.pickle"%(temporary_dir,pid,sv_type), "rb") as f:                
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                      
FileNotFoundError: [Errno 2] No such file or directory: './signatures/107DEL.pickle'             
"""                                                                                              
```

I think there are several issues around the way `Pool` is used in the main function. 

- Manual calls to `close()` and `join()` could be replaced by using the pool as a context manager
- The results of `map_async(...)` at [line 1069](https://github.com/tjiangHIT/cuteSV/blob/master/src/cuteSV/cuteSV#L1069) are not captured and explicitly waited
- `result.get()` is called *after* `close()` and `join()` at [line 1084](https://github.com/tjiangHIT/cuteSV/blob/master/src/cuteSV/cuteSV#L1084)

I cannot be certain that any of these are the cause of the missing file error but not waiting for for the results with `result.get` in particular can be problematic, because `close()` and `join()` will swallow any exceptions from the child processes.

**Comment by Meltpinkg** [comment]
Hello, @awgymer 

Thank you for your valuable suggestions regarding the potential issues in the multi-process design of cuteSV. We have merged the PR. These modifications indeed enhance the robustness of the multi-processing and help prevent errors.  We will release this latest version to Bioconda and PyPI after the baseline tests.
Thanks again for your help with this issue.

Best regards,
Shuqi

**Comment by mulderdt** [comment]
This ended up being a NFS race condition. In my nextflow workflow I resolved my staging the reference files and work folder in the node's local disk.
So you can do something like this
`#prevent spawning more threads by htslib. cutesv already has a threads parameter
export OMP_NUM_THREADS=1

#avoid cuteSV i/o failure (NFS race condition for pickle files) by doing work in local disk
#make sure this process has multiple reattempts in the nextflow.config file so in the event of failure in case the job is dispatched to a node where the /var/tmp is disk space is full
TMPDIR=$(mktemp -d "/var/tmp/nxf_tmp.$(hostname).${SLURM_JOB_ID:-$$}.XXXXXX")

#define a function to cleanup the temp dir
_cleanup() {
    echo "Cleaning TMPDIR: \$TMPDIR" >&2
    bash ${params.cleanup_tempdir} "\$TMPDIR"
}

#establish a trap to run the clean up function in the event of a failure
trap '_cleanup' EXIT TERM INT HUP

#move the reference to the temp space to prevent failures
cp ${params.reference_fasta} \${TMPDIR}
cp ${params.reference_fai} \${TMPDIR}
REF=\$(find \$TMPDIR -name "*.fa")

cuteSV \
    --sample ${trio_id}_${relation} \
    --threads 4 \
    -md 500 \
    -mi 500 \
    -s 5 \
    -L -1 \
    --genotype \
    ${bam} \
    ${REF} \
    ${trio_id}_${relation}_cuteSV.vcf \
    \$TMPDIR`

Oddly the escape characters aren't printing in the comment so if you implement in nextflow note that those need be escaped.
