### ISSUE TITLE
IndexError when force calling translocations

### ISSUE THREAD

**Issue by wdecoster** [tjiangHIT/cuteSV#40]
Hi,

I did the following with cuteSV 1.0.10:

1) CuteSV SV calling
2) merging the VCFs with [Jasmine](https://github.com/mkirsche/Jasmine)
3) CuteSV force calling with -Ivcf

However, the last step generates the following error:
```
Traceback (most recent call last):
  File "/home/wdecoster/miniconda3/envs/cutesv/bin/cuteSV", line 4, in <module>
    __import__('pkg_resources').run_script('cuteSV==1.0.10', 'cuteSV')
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/cuteSV-1.0.10-py3.8.egg/EGG-INFO/scripts/cuteSV", line 801, in <module>
    run(sys.argv[1:])
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/cuteSV-1.0.10-py3.8.egg/EGG-INFO/scripts/cuteSV", line 797, in run
    main_ctrl(args, argv)
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/cuteSV-1.0.10-py3.8.egg/EGG-INFO/scripts/cuteSV", line 671, in main_ctrl
    result = force_calling(args.input, args.Ivcf, args.output, temporary_dir,
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/cuteSV-1.0.10-py3.8.egg/cuteSV/cuteSV_forcecalling.py", line 334, in force_calling
    sv_type, chrom, sv_chr2, pos, sv_end, sv_strand = parse_record(record)
  File "/home/wdecoster/miniconda3/envs/cutesv/lib/python3.8/site-packages/cuteSV-1.0.10-py3.8.egg/cuteSV/cuteSV_forcecalling.py", line 73, in parse_record
    end = int(tra_alt.split(':')[1])
IndexError: list index out of range
```

I am afraid I can't share the VCF or bam files with you to reproduce this. Based on the error I suspect it is something with translocations, and removing these from the jasmine-merged file solves the error. I will show you how the first nine columns of TRA records look like after merging with Jasmine:

```
chr11   18643255        0_cuteSV.BND.0  .       <TRA>   219.5   PASS    PRECISE;SVTYPE=TRA;RE=23;RNAMES=1d499825-dfb5-45ea-98a5-fe16cf6541f5,88f6b37c-5f2c-4321-9ce9-d7fa63fb1b3c,8f28177b-de81-4ecd-aba7-37263a2f7f05,de9e5e07-2fcf-4677-a7df-c53d3607a2ba,b5d8446a-be7a-41d1-8c66-6069fceae18e,b1816320-0708-44e8-a75c-72f3dd4685f6,d1359d10-8ddd-4ff2-87b5-aa46fac52d87,5172ee36-fe44-4a8a-974c-f624e56b2526,4320724c-87d4-4847-a1a8-6e92cb7d78f3,68cda33f-1af3-4138-88de-af9d9c8da685,10867622-47fd-40d5-8e7f-ac25ae380431,493637b1-03ae-489d-bbb2-632d3cf83369,7979d796-bf1b-4d18-beee-b1f993c2c287,04821c5c-d4da-4dc2-80f9-1442b5ddb72a,6ec55480-0de9-4e0d-b0e3-16b6d843e7bc,6931cc19-5fcd-4b0a-a535-42c48ec7ccaa,ff16f2ba-1beb-4785-a800-2077dcb4e1fb,0520b923-f1d1-4bcc-948f-9011d36607cc,032622cf-9222-43b3-a146-30b7a074c261,a96cca8a-18c7-4286-b116-77ccde9d5a4e,cde75c30-857d-44e5-8d45-148e30614c9f,b3ddb5cd-6054-489e-903d-2608821eefda,8b89de4d-980c-4a60-984a-ffb498abb866;IRIS_PROCESSED=1;IRIS_REFINED=0;CHR2=chr15;END=34376485;STRANDS=--;SVLEN=0;STARTVARIANCE=645871785781648.800000;ENDVARIANCE=1291743571563295.200000;AVG_LEN=0.000000;AVG_START=18643256.792899;AVG_END=34376486.769231;SUPP_VEC_EXT=101000110111110111000111111010011011111111011101110001000101011000010100001010000110000111100100011101110111011100011110101011111101111101100000000010010100100001011111111110111111101110110000110000100111100110110100011101101101110110100001110000111010110001000110111010001111011111101101111010000000001010;IDLIST_EXT=cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0;SUPP_EXT=169;SUPP_VEC=101000110111110111000111111010011011111111011101110001000101011000010100001010000110000111100100011101110111011100011110101011111101111101100000000010010100100001011111111110111111101110110000110000100111100110110100011101101101110110100001110000111010110001000110111010001111011111101101111010000000001010;SUPP=169;SVMETHOD=JASMINE;IDLIST=cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0,cuteSV.BND.0        GT:IS:OT:OS:DV:DR       
chr11   18649472        0_cuteSV.BND.1  .       <TRA>   51.9    PASS    PRECISE;SVTYPE=TRA;RE=14;RNAMES=04821c5c-d4da-4dc2-80f9-1442b5ddb72a,8f28177b-de81-4ecd-aba7-37263a2f7f05,1d499825-dfb5-45ea-98a5-fe16cf6541f5,de9e5e07-2fcf-4677-a7df-c53d3607a2ba,10867622-47fd-40d5-8e7f-ac25ae380431,b5d8446a-be7a-41d1-8c66-6069fceae18e,6931cc19-5fcd-4b0a-a535-42c48ec7ccaa,88f6b37c-5f2c-4321-9ce9-d7fa63fb1b3c,032622cf-9222-43b3-a146-30b7a074c261,cde75c30-857d-44e5-8d45-148e30614c9f,b3ddb5cd-6054-489e-903d-2608821eefda,7979d796-bf1b-4d18-beee-b1f993c2c287,5172ee36-fe44-4a8a-974c-f624e56b2526,4320724c-87d4-4847-a1a8-6e92cb7d78f3;IRIS_PROCESSED=1;IRIS_REFINED=0;CHR2=chr15;END=34376063;STRANDS=++;SVLEN=0;STARTVARIANCE=3.312500;ENDVARIANCE=1611210068452230.000000;AVG_LEN=0.000000;AVG_START=18649474.859813;AVG_END=34376059.794393;SUPP_VEC_EXT=101000010011111111000011111000000000101111011100110000010101011000000100000000000000000100000100011100010111011100001010101011011000111100000000000010010100000001001111110000111010000110010000100000000110100100100000011001000001110100100000000000010010110001000010101010001001010011001101010010000000000010;IDLIST_EXT=cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.0,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.0,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1;SUPP_EXT=107;SUPP_VEC=101000010011111111000011111000000000101111011100110000010101011000000100000000000000000100000100011100010111011100001010101011011000111100000000000010010100000001001111110000111010000110010000100000000110100100100000011001000001110100100000000000010010110001000010101010001001010011001101010010000000000010;SUPP=107;SVMETHOD=JASMINE;IDLIST=cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.0,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.0,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1,cuteSV.BND.1       GT:IS:OT:OS:DV:DR

```

Hope that helps!

Cheers,
Wouter

**Comment by tjiangHIT** [comment]
Hello Wouter,

Thanks for pointing this out.
The example is very helpful for fixing this error.
Please git clone the latest codes to try again.

Best,
Tao

**Comment by tjiangHIT** [comment]
Hello @wdecoster,

I just now update cuteSV to v1.0.12, and cuteSV can be installed from pip or conda (may be delayed by 1-2 days).
Please have a new trial.
Thanks for your suggestion.

Best,
Tao

**Comment by wdecoster** [comment]
Thanks - I have just merged the updated version on bioconda (https://github.com/bioconda/bioconda-recipes/pull/30844).
