### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by TrinidadMartin** [tjiangHIT/cuteSV#52]
Hello!!

I have tried both:

`conda install -c bioconda cutesv`
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                               

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

and 
`git clone https://github.com/tjiangHIT/cuteSV.git && cd cuteSV/ && python setup.py install`

Cloning into 'cuteSV'...
remote: Enumerating objects: 940, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 940 (delta 59), reused 73 (delta 32), pack-reused 817
Receiving objects: 100% (940/940), 2.98 MiB | 18.25 MiB/s, done.
Resolving deltas: 100% (515/515), done.
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
running install
running bdist_egg
running egg_info
creating src/cuteSV.egg-info
writing requirements to src/cuteSV.egg-info/requires.txt
writing src/cuteSV.egg-info/PKG-INFO
writing top-level names to src/cuteSV.egg-info/top_level.txt
writing dependency_links to src/cuteSV.egg-info/dependency_links.txt
writing manifest file 'src/cuteSV.egg-info/SOURCES.txt'
reading manifest file 'src/cuteSV.egg-info/SOURCES.txt'
writing manifest file 'src/cuteSV.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/cuteSV
copying src/cuteSV/cuteSV_resolveTRA.py -> build/lib/cuteSV
copying src/cuteSV/cuteSV_forcecalling.py -> build/lib/cuteSV
copying src/cuteSV/cuteSV_resolveINV.py -> build/lib/cuteSV
copying src/cuteSV/__init__.py -> build/lib/cuteSV
copying src/cuteSV/cuteSV_resolveDUP.py -> build/lib/cuteSV
copying src/cuteSV/cuteSV_genotype.py -> build/lib/cuteSV
copying src/cuteSV/CommandRunner.py -> build/lib/cuteSV
copying src/cuteSV/cuteSV_Description.py -> build/lib/cuteSV
copying src/cuteSV/diploid_calling.py -> build/lib/cuteSV
copying src/cuteSV/cuteSV_resolveINDEL.py -> build/lib/cuteSV
creating build/lib/benchmarks
copying src/benchmarks/eval_sim.py -> build/lib/benchmarks
copying src/benchmarks/sta_venn.py -> build/lib/benchmarks
copying src/benchmarks/__init__.py -> build/lib/benchmarks
copying src/benchmarks/eval_trio.py -> build/lib/benchmarks
copying src/benchmarks/vcf2bedpe.py -> build/lib/benchmarks
copying src/benchmarks/cmp_NA19240.py -> build/lib/benchmarks
copying src/benchmarks/multi_platform.py -> build/lib/benchmarks
creating build/bdist.macosx-10.13-x86_64
creating build/bdist.macosx-10.13-x86_64/egg
creating build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_resolveTRA.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_forcecalling.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_resolveINV.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/__init__.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_resolveDUP.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_genotype.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/CommandRunner.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_Description.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/diploid_calling.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
copying build/lib/cuteSV/cuteSV_resolveINDEL.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
creating build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/eval_sim.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/sta_venn.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/__init__.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/eval_trio.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/vcf2bedpe.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/cmp_NA19240.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
copying build/lib/benchmarks/multi_platform.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveTRA.py to cuteSV_resolveTRA.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_forcecalling.py to cuteSV_forcecalling.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveINV.py to cuteSV_resolveINV.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveDUP.py to cuteSV_resolveDUP.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_genotype.py to cuteSV_genotype.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/CommandRunner.py to CommandRunner.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_Description.py to cuteSV_Description.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/diploid_calling.py to diploid_calling.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveINDEL.py to cuteSV_resolveINDEL.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/eval_sim.py to eval_sim.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/sta_venn.py to sta_venn.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/eval_trio.py to eval_trio.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/vcf2bedpe.py to vcf2bedpe.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/cmp_NA19240.py to cmp_NA19240.pyc
byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/multi_platform.py to multi_platform.pyc
installing package data to build/bdist.macosx-10.13-x86_64/egg
running install_data
copying LICENSE -> build/bdist.macosx-10.13-x86_64/egg/
creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting src/cuteSV/cuteSV -> build/scripts-2.7
changing mode of build/scripts-2.7/cuteSV from 644 to 755
creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/cuteSV -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts/cuteSV to 755
copying src/cuteSV.egg-info/PKG-INFO -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying src/cuteSV.egg-info/SOURCES.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying src/cuteSV.egg-info/dependency_links.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying src/cuteSV.egg-info/not-zip-safe -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying src/cuteSV.egg-info/requires.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
copying src/cuteSV.egg-info/top_level.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
creating dist
creating 'dist/cuteSV-1.0.11-py2.7.egg' and adding 'build/bdist.macosx-10.13-x86_64/egg' to it
removing 'build/bdist.macosx-10.13-x86_64/egg' (and everything under it)
Processing cuteSV-1.0.11-py2.7.egg
removing '/usr/local/lib/python2.7/site-packages/cuteSV-1.0.11-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/cuteSV-1.0.11-py2.7.egg
Extracting cuteSV-1.0.11-py2.7.egg to /usr/local/lib/python2.7/site-packages
cuteSV 1.0.11 is already the active version in easy-install.pth
Installing cuteSV script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/cuteSV-1.0.11-py2.7.egg
Processing dependencies for cuteSV==1.0.11
Searching for pyvcf
Reading https://pypi.org/simple/pyvcf/
Download error on https://pypi.org/simple/pyvcf/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'pyvcf' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for pyvcf
error: Could not find suitable distribution for Requirement.parse('pyvcf')

Pyvcf is installed
`conda install -c conda-forge pyvcf`
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Thanks a lot!!
T

**Comment by TrinidadMartin** [comment]
> Hello!!
> 
> I have tried both:
> 
> `conda install -c bioconda cutesv`
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes. Press CTRL-C to abort.
> failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versions
> 
> and
> `git clone https://github.com/tjiangHIT/cuteSV.git && cd cuteSV/ && python setup.py install`
> 
> Cloning into 'cuteSV'...
> remote: Enumerating objects: 940, done.
> remote: Counting objects: 100% (123/123), done.
> remote: Compressing objects: 100% (91/91), done.
> remote: Total 940 (delta 59), reused 73 (delta 32), pack-reused 817
> Receiving objects: 100% (940/940), 2.98 MiB | 18.25 MiB/s, done.
> Resolving deltas: 100% (515/515), done.
> ERROR:root:code for hash md5 was not found.
> Traceback (most recent call last):
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in
> globals()[__func_name] = __get_hash(__func_name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
> raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> ERROR:root:code for hash sha1 was not found.
> Traceback (most recent call last):
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in
> globals()[__func_name] = __get_hash(__func_name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
> raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> ERROR:root:code for hash sha224 was not found.
> Traceback (most recent call last):
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in
> globals()[__func_name] = __get_hash(__func_name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
> raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha224
> ERROR:root:code for hash sha256 was not found.
> Traceback (most recent call last):
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in
> globals()[__func_name] = __get_hash(__func_name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
> raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha256
> ERROR:root:code for hash sha384 was not found.
> Traceback (most recent call last):
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in
> globals()[__func_name] = __get_hash(__func_name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
> raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha384
> ERROR:root:code for hash sha512 was not found.
> Traceback (most recent call last):
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in
> globals()[__func_name] = __get_hash(__func_name)
> File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
> raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha512
> running install
> running bdist_egg
> running egg_info
> creating src/cuteSV.egg-info
> writing requirements to src/cuteSV.egg-info/requires.txt
> writing src/cuteSV.egg-info/PKG-INFO
> writing top-level names to src/cuteSV.egg-info/top_level.txt
> writing dependency_links to src/cuteSV.egg-info/dependency_links.txt
> writing manifest file 'src/cuteSV.egg-info/SOURCES.txt'
> reading manifest file 'src/cuteSV.egg-info/SOURCES.txt'
> writing manifest file 'src/cuteSV.egg-info/SOURCES.txt'
> installing library code to build/bdist.macosx-10.13-x86_64/egg
> running install_lib
> running build_py
> creating build
> creating build/lib
> creating build/lib/cuteSV
> copying src/cuteSV/cuteSV_resolveTRA.py -> build/lib/cuteSV
> copying src/cuteSV/cuteSV_forcecalling.py -> build/lib/cuteSV
> copying src/cuteSV/cuteSV_resolveINV.py -> build/lib/cuteSV
> copying src/cuteSV/**init**.py -> build/lib/cuteSV
> copying src/cuteSV/cuteSV_resolveDUP.py -> build/lib/cuteSV
> copying src/cuteSV/cuteSV_genotype.py -> build/lib/cuteSV
> copying src/cuteSV/CommandRunner.py -> build/lib/cuteSV
> copying src/cuteSV/cuteSV_Description.py -> build/lib/cuteSV
> copying src/cuteSV/diploid_calling.py -> build/lib/cuteSV
> copying src/cuteSV/cuteSV_resolveINDEL.py -> build/lib/cuteSV
> creating build/lib/benchmarks
> copying src/benchmarks/eval_sim.py -> build/lib/benchmarks
> copying src/benchmarks/sta_venn.py -> build/lib/benchmarks
> copying src/benchmarks/**init**.py -> build/lib/benchmarks
> copying src/benchmarks/eval_trio.py -> build/lib/benchmarks
> copying src/benchmarks/vcf2bedpe.py -> build/lib/benchmarks
> copying src/benchmarks/cmp_NA19240.py -> build/lib/benchmarks
> copying src/benchmarks/multi_platform.py -> build/lib/benchmarks
> creating build/bdist.macosx-10.13-x86_64
> creating build/bdist.macosx-10.13-x86_64/egg
> creating build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_resolveTRA.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_forcecalling.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_resolveINV.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/**init**.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_resolveDUP.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_genotype.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/CommandRunner.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_Description.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/diploid_calling.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> copying build/lib/cuteSV/cuteSV_resolveINDEL.py -> build/bdist.macosx-10.13-x86_64/egg/cuteSV
> creating build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/eval_sim.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/sta_venn.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/**init**.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/eval_trio.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/vcf2bedpe.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/cmp_NA19240.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> copying build/lib/benchmarks/multi_platform.py -> build/bdist.macosx-10.13-x86_64/egg/benchmarks
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveTRA.py to cuteSV_resolveTRA.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_forcecalling.py to cuteSV_forcecalling.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveINV.py to cuteSV_resolveINV.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/**init**.py to **init**.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveDUP.py to cuteSV_resolveDUP.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_genotype.py to cuteSV_genotype.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/CommandRunner.py to CommandRunner.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_Description.py to cuteSV_Description.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/diploid_calling.py to diploid_calling.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/cuteSV/cuteSV_resolveINDEL.py to cuteSV_resolveINDEL.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/eval_sim.py to eval_sim.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/sta_venn.py to sta_venn.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/**init**.py to **init**.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/eval_trio.py to eval_trio.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/vcf2bedpe.py to vcf2bedpe.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/cmp_NA19240.py to cmp_NA19240.pyc
> byte-compiling build/bdist.macosx-10.13-x86_64/egg/benchmarks/multi_platform.py to multi_platform.pyc
> installing package data to build/bdist.macosx-10.13-x86_64/egg
> running install_data
> copying LICENSE -> build/bdist.macosx-10.13-x86_64/egg/
> creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> installing scripts to build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts
> running install_scripts
> running build_scripts
> creating build/scripts-2.7
> copying and adjusting src/cuteSV/cuteSV -> build/scripts-2.7
> changing mode of build/scripts-2.7/cuteSV from 644 to 755
> creating build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts
> copying build/scripts-2.7/cuteSV -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts
> changing mode of build/bdist.macosx-10.13-x86_64/egg/EGG-INFO/scripts/cuteSV to 755
> copying src/cuteSV.egg-info/PKG-INFO -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> copying src/cuteSV.egg-info/SOURCES.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> copying src/cuteSV.egg-info/dependency_links.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> copying src/cuteSV.egg-info/not-zip-safe -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> copying src/cuteSV.egg-info/requires.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> copying src/cuteSV.egg-info/top_level.txt -> build/bdist.macosx-10.13-x86_64/egg/EGG-INFO
> creating dist
> creating 'dist/cuteSV-1.0.11-py2.7.egg' and adding 'build/bdist.macosx-10.13-x86_64/egg' to it
> removing 'build/bdist.macosx-10.13-x86_64/egg' (and everything under it)
> Processing cuteSV-1.0.11-py2.7.egg
> removing '/usr/local/lib/python2.7/site-packages/cuteSV-1.0.11-py2.7.egg' (and everything under it)
> creating /usr/local/lib/python2.7/site-packages/cuteSV-1.0.11-py2.7.egg
> Extracting cuteSV-1.0.11-py2.7.egg to /usr/local/lib/python2.7/site-packages
> cuteSV 1.0.11 is already the active version in easy-install.pth
> Installing cuteSV script to /usr/local/bin
> 
> Installed /usr/local/lib/python2.7/site-packages/cuteSV-1.0.11-py2.7.egg
> Processing dependencies for cuteSV==1.0.11
> Searching for pyvcf
> Reading https://pypi.org/simple/pyvcf/
> Download error on https://pypi.org/simple/pyvcf/: unknown url type: https -- Some packages may not be found!
> Couldn't find index page for 'pyvcf' (maybe misspelled?)
> Scanning index of all packages (this may take a while)
> Reading https://pypi.org/simple/
> Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
> No local packages or working download links found for pyvcf
> error: Could not find suitable distribution for Requirement.parse('pyvcf')
> 
> Pyvcf is installed
> `conda install -c conda-forge pyvcf`
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> # All requested packages already installed.
> Thanks a lot!!
> T

Bad installation of the pyvcf package
I did 
`conda config --add channels conda-forge
conda install pyvcf`
and now it is working ;)
