### ISSUE TITLE
execution error 

### ISSUE THREAD

**Issue by TrinidadMartin** [tjiangHIT/cuteSV#53]
Hello!!

I am trying to run cuteSV with my PacBio yeast data and I get this error:

`cuteSV /Users/io/Documents/TB50/SVs/PacBio_alignedReads_pbmm2.sorted.bam /Users/io/Documents/TB50/SVs/Final_SV_calling/reference_genome/S288C_genome.fasta cuteSV_PB.vcf /Users/io/Documents/TB50/SVs/Final_SV_calling/cuteSV/results --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 200 --diff_ratio_merging_DEL 0.5`
2021-09-08 10:15:41,613 [INFO] Running /Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/bin/cuteSV /Users/io/Documents/TB50/SVs/PacBio_alignedReads_pbmm2.sorted.bam /Users/io/Documents/TB50/SVs/Final_SV_calling/reference_genome/S288C_genome.fasta cuteSV_PB.vcf /Users/io/Documents/TB50/SVs/Final_SV_calling/cuteSV/results --max_cluster_bias_INS 100 --diff_ratio_merging_INS 0.3 --max_cluster_bias_DEL 200 --diff_ratio_merging_DEL 0.5
2021-09-08 10:15:41,661 [INFO] The total number of chromsomes: 17
Traceback (most recent call last):
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/bin/cuteSV", line 4, in <module>
    __import__('pkg_resources').run_script('cuteSV==1.0.11', 'cuteSV')
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/site-packages/cuteSV-1.0.11-py3.9.egg/EGG-INFO/scripts/cuteSV", line 802, in <module>
    run(sys.argv[1:])
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/site-packages/cuteSV-1.0.11-py3.9.egg/EGG-INFO/scripts/cuteSV", line 798, in run
    main_ctrl(args, argv)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/site-packages/cuteSV-1.0.11-py3.9.egg/EGG-INFO/scripts/cuteSV", line 627, in main_ctrl
    analysis_pools = Pool(processes=int(args.threads))
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/io/Documents/TB50/SVs/Final_SV_calling/sv_callers/software/sv-callers/miniconda3/lib/python3.9/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

Any idea??
Thanks!
T

**Comment by Meltpinkg** [comment]
Hello, @TrinidadMartin, 

Based on your description, it seems like a problem on the version of multiprocessing package that caused by the inconsistent version of python. Besides, there might be some different settings between Linux and Windows as well. By far we have successfully tested cuteSV on **Linux** platform with python **3.8** . I strongly recommend you retry cuteSV with python 3.8 in your environment.
Hope it will help!

Best,
Shuqi
