### ISSUE TITLE
Force calling

### ISSUE THREAD

**Issue by Akazhiel** [tjiangHIT/cuteSV#80]
Hello!

I've tried to use cuteSV to forcecall variants in a VCF found with another tool but I've come across this error:
```
Traceback (most recent call last):
  File "/opt/conda/envs/Nanopore_WGS/bin/cuteSV", line 4, in <module>
    __import__('pkg_resources').run_script('cuteSV==1.0.13', 'cuteSV')
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/cuteSV-1.0.13-py3.7.egg/EGG-INFO/scripts/cuteSV", line 801, in <module>
    run(sys.argv[1:])
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/cuteSV-1.0.13-py3.7.egg/EGG-INFO/scripts/cuteSV", line 797, in run
    main_ctrl(args, argv)
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/cuteSV-1.0.13-py3.7.egg/EGG-INFO/scripts/cuteSV", line 671, in main_ctrl
    max_cluster_bias_dict, threshold_gloab_dict, args.gt_round, args.threads)
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/cuteSV-1.0.13-py3.7.egg/cuteSV/cuteSV_forcecalling.py", line 424, in force_calling
    sv_dict['TRA'] = parse_trasigs(sigs_dir)
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/cuteSV-1.0.13-py3.7.egg/cuteSV/cuteSV_forcecalling.py", line 180, in parse_trasigs
    pos2 = int(seq[5])
ValueError: invalid literal for int() with base 10: 'ATTGTRATTTGTRGYGGYTMCCACRARRGTCTGCAGCTTCASTCTTGAGCCCAGCGAGGCCATGAGCCCACSRGGAGGAATGAACAACTCCAGACGCTCCAC'
``` 

I've noticed for some reason in the `TRA.sigs` file that is generated, the first lines don't actually correspond to a translocation but they correspond to insertions that are labelled as `<INS>` in the VCF.

Best regards,
Jonatan

**Comment by Meltpinkg** [comment]
Hello, @Akazhiel 

It seems that we haven't come across the similar condition as the error you mentioned. Can you please provide the command of running cuteSV, and the corresponding line in `TRA.sigs`? It will be helpful for us to solve this error.
Thanks for reporting the error!

Best regards,
Shuqi

**Comment by Meltpinkg** [comment]
Hello, @Akazhiel 

This error happened when extracting SV signatures from our temporary file. As the sigs you provided above, there is a subsequence "TRA" in the sequence of the insertion. So it is extracted into TRA.sigs by mistake.
We changed the way of extracting the signatures to avoid the error. And after our test it runs successfully now.
Please git clone the latest codes and check it.

Best regards,
Shuqi
