### ISSUE TITLE
diploid_calling.py   AttributeError: module 'vcf' has no attribute 'Reader'

### ISSUE THREAD

**Issue by Chenglin20170390** [tjiangHIT/cuteSV#86]
Hi  when I use diploid_calling.py to call sv from assembly genome follow your dipcall pipline ```

https://github.com/tjiangHIT/cuteSV/wiki/Diploid-assembly-based-SV-detection-using-cuteSV`, it occur  an error
```
Traceback (most recent call last):
  File "/home/chenglin/softwares/miniconda3/envs/cuteSV/bin/diploid_calling.py", line 111, in <module>
    main(sys.argv[1:])
  File "/home/chenglin/softwares/miniconda3/envs/cuteSV/bin/diploid_calling.py", line 88, in main
    main_ctrl(args)
  File "/home/chenglin/softwares/miniconda3/envs/cuteSV/bin/diploid_calling.py", line 30, in main_ctrl
    filein = vcf.Reader(open(args.invcf, 'r'))
AttributeError: module 'vcf' has no attribute 'Reader'

```

**Comment by Chenglin20170390** [comment]
solved by reinstall
